service: middy-redis-cache
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: ap-south-1
  profile: rajath-aws-admin-user

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get
